name: genvalidity-hspec-optics
version: '0.1.0.0'
synopsis: Standard spec's for optics
description: Standard spec's for optics
category: Testing
author: Tom Sydney Kerckhove
maintainer:
- syd.kerckhove@gmail.com
- nick.van.den.broeck666@gmail.com
copyright: ! 'Copyright: (c) 2018 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
homepage: http://cs-syd.eu
dependencies:
- hspec

library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Test.Validity.Optics
  dependencies:
  - base >=4.9 && <=5
  - genvalidity >=0.5
  - microlens
  - QuickCheck
  - genvalidity-hspec

tests:
  genvalidity-hspec-optics-doctests:
    main: DocTest.hs
    source-dirs: doctest
    ghc-options: -threaded
    dependencies:
    - base
    - doctest
    - genvalidity-hspec-optics
  genvalidity-hspec-optics-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - microlens
    - base
    - genvalidity
    - genvalidity-hspec
    - genvalidity-hspec-optics
