name: genvalidity-hspec-persistent
version: '0.0.0.0'
synopsis: Standard spec's for persistent-related instances
description: Standard spec's for persistent-related Instances
category: Testing
author: Tom Sydney Kerckhove
maintainer:
- syd.kerckhove@gmail.com
- nick.van.den.broeck666@gmail.com
copyright: ! 'Copyright: (c) 2019 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
homepage: http://cs-syd.eu
dependencies:
- hspec

library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Test.Validity.Persist
  dependencies:
  - base >=4.9 && <=5
  - QuickCheck
  - genvalidity >=0.5
  - genvalidity-hspec >=0.6
  - persistent
  - text

tests:
  genvalidity-hspec-persistent-doctests:
    main: DocTest.hs
    source-dirs: doctest
    ghc-options: -threaded
    dependencies:
    - base
    - doctest
    - genvalidity >=0.7
    - genvalidity-hspec
    - genvalidity-hspec-persistent
    - genvalidity-property >=0.3
    - persistent
    - text
    - validity >=0.9

  genvalidity-hspec-persistent-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - base
    - genvalidity >=0.7
    - genvalidity-hspec
    - genvalidity-hspec-persistent
    - genvalidity-property >=0.3
    - genvalidity-text
    - persistent
    - text
    - validity >=0.9
