name: genvalidity-hspec-persistent
version: '0.0.0.0'
synopsis: Standard spec's for persistent-related instances
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2019-2020 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
homepage: http://cs-syd.eu
dependencies:
- base >=4.9 && <=5
- hspec
- persistent

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - QuickCheck
  - genvalidity >=0.5
  - genvalidity-hspec >=0.6
  - text

tests:
  genvalidity-hspec-persistent-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - genvalidity >=0.7
    - genvalidity-hspec
    - genvalidity-hspec-persistent
    - genvalidity-property >=0.3
    - genvalidity-text
    - text
    - validity >=0.9
