- ignore: { name: "Use forM_" }
- ignore: { name: "Redundant bracket" }
- ignore: { name: "Use <$>" }
- ignore: { name: "Use ++" }
- ignore: { name: "Use min" }
- ignore: { name: "Use max" }
- ignore: { name: "Use unless" }
- ignore: { name: "Use uncurry" }
- ignore: { name: "Use <&>" }
- ignore: { name: "Redundant <$>" }
- ignore: { name: "Avoid lambda using `infix`" }
