sudo: false
language: c

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

matrix:
  include:
  - env: ARGS="--stack-yaml lts-8.yaml"
    compiler: ": #stack GHC-8.0.2"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--stack-yaml lts-7.yaml"
    compiler: ": #stack GHC-8.0.1"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--stack-yaml lts-6.yaml"
    compiler: ": #stack GHC-7.10.3"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--stack-yaml lts-3.yaml"
    compiler: ": #stack GHC-7.10.2"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--stack-yaml lts-2.yaml"
    compiler: ": #stack GHC-7.8.4"
    addons: {apt: {packages: [libgmp-dev]}}

  # Nightly builds are allowed to fail
  - env: ARGS="--resolver nightly"
    compiler: ": #stack nightly"
    addons: {apt: {packages: [libgmp-dev]}}

  allow_failures:
  - env: ARGS="--resolver nightly"

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - chmod a+x ~/.local/bin/stack

install:
- stack +RTS -N2 -RTS setup
- stack +RTS -N2 -RTS build --only-snapshot
- stack +RTS -N2 -RTS install hindent
- stack +RTS -N2 -RTS install cabal-install

script:
- git --version
- stack --version
- stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
