packages:
- 'genvalidity'
- 'genvalidity-containers'
- 'genvalidity-hspec'
- 'genvalidity-hspec-aeson'
- 'genvalidity-hspec-cereal'
- 'genvalidity-path'
- 'genvalidity-text'
- 'genvalidity-time'
- 'validity'
- 'validity-bytestring'
- 'validity-containers'
- 'validity-path'
- 'validity-text'
- 'validity-time'
extra-deps: []
flags: {}
extra-package-dbs: []
resolver: lts-7.14
