resolver: lts-19.6
packages:
- 'genvalidity'
- 'genvalidity-aeson'
- 'genvalidity-bytestring'
- 'genvalidity-case-insensitive'
- 'genvalidity-containers'
- 'genvalidity-criterion'
- 'genvalidity-hspec'
- 'genvalidity-hspec-aeson'
- 'genvalidity-hspec-binary'
- 'genvalidity-hspec-cereal'
- 'genvalidity-hspec-hashable'
- 'genvalidity-hspec-optics'
- 'genvalidity-hspec-persistent'
- 'genvalidity-network-uri'
- 'genvalidity-path'
- 'genvalidity-persistent'
- 'genvalidity-property'
- 'genvalidity-scientific'
- 'genvalidity-sydtest'
- 'genvalidity-sydtest-aeson'
- 'genvalidity-sydtest-hashable'
- 'genvalidity-sydtest-lens'
- 'genvalidity-sydtest-persistent'
- 'genvalidity-text'
- 'genvalidity-time'
- 'genvalidity-unordered-containers'
- 'genvalidity-uuid'
- 'genvalidity-vector'
- 'validity'
- 'validity-aeson'
- 'validity-bytestring'
- 'validity-case-insensitive'
- 'validity-containers'
- 'validity-network-uri'
- 'validity-path'
- 'validity-persistent'
- 'validity-primitive'
- 'validity-scientific'
- 'validity-text'
- 'validity-time'
- 'validity-unordered-containers'
- 'validity-uuid'
- 'validity-vector'


extra-deps:
- github: NorfairKing/autodocodec
  commit: 98135d2b24c4c52f56f53c6650a169aeec61c7f1
  subdirs:
    - autodocodec
    - autodocodec-schema
    - autodocodec-yaml

- github: NorfairKing/safe-coloured-text
  commit: 675cb01fce5f46718416d7746de5b856ed90a63f
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

- github: NorfairKing/sydtest
  commit: 9db39de44641f28a2c26de80fcfe08616fcf3054
  subdirs:
    - sydtest
    - sydtest-discover

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef

system-ghc: true
nix:
  enable: false
with-hpack: hpack
