packages:
- 'genvalidity'
- 'genvalidity-bytestring'
- 'genvalidity-containers'
- 'genvalidity-hspec'
- 'genvalidity-hspec-aeson'
- 'genvalidity-hspec-binary'
- 'genvalidity-hspec-cereal'
- 'genvalidity-hspec-hashable'
- 'genvalidity-path'
- 'genvalidity-property'
- 'genvalidity-scientific'
- 'genvalidity-text'
- 'genvalidity-time'
- 'validity'
- 'validity-bytestring'
- 'validity-containers'
- 'validity-path'
- 'validity-scientific'
- 'validity-text'
- 'validity-time'
resolver: lts-8.5
