packages:
- 'validity'
- 'validity-containers'
- 'validity-text'
- 'validity-bytestring'
- 'genvalidity'
- 'genvalidity-containers'
- 'genvalidity-text'
- 'genvalidity-hspec'
extra-deps: []
flags: {}
extra-package-dbs: []
resolver: lts-7.14
