resolver: lts-15.10
packages:
- 'genvalidity'
- 'genvalidity-aeson'
- 'genvalidity-bytestring'
- 'genvalidity-containers'
- 'genvalidity-criterion'
- 'genvalidity-hspec'
- 'genvalidity-hspec-aeson'
- 'genvalidity-hspec-binary'
- 'genvalidity-hspec-cereal'
- 'genvalidity-hspec-hashable'
- 'genvalidity-hspec-optics'
- 'genvalidity-hspec-persistent'
- 'genvalidity-path'
- 'genvalidity-property'
- 'genvalidity-scientific'
- 'genvalidity-text'
- 'genvalidity-time'
- 'genvalidity-unordered-containers'
- 'genvalidity-uuid'
- 'genvalidity-vector'
- 'validity'
- 'validity-aeson'
- 'validity-bytestring'
- 'validity-containers'
- 'validity-path'
- 'validity-primitive'
- 'validity-scientific'
- 'validity-text'
- 'validity-time'
- 'validity-unordered-containers'
- 'validity-uuid'
- 'validity-vector'
nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/f9b8d17c100681fde8dde58fa794527f0159c9ee.tar.gz"]
  add-gc-roots: true
  pure: true
  packages:
  - zlib
  - haskellPackages.hpack
