name: genvalidity-criterion
version: '0.0.0.0'
synopsis: Criterion benchmarks for generators
category: Validity
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2018-2020 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity

dependencies:
- base <5
- criterion

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - deepseq
  - genvalidity

benchmarks:
  genvalidity-criterion-bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options:
    - -Wall
    dependencies:
    - QuickCheck
    - genvalidity
    - genvalidity-criterion
