name: genvalidity-text
version: '1.0.0.0'
synopsis: GenValidity support for Text
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2016-2021 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity

extra-source-files:
- LICENSE
- CHANGELOG.md

dependencies:
- base >=4.7 && <5
- text
- QuickCheck

library:
  source-dirs: src
  dependencies:
  - array
  - genvalidity >=1.0
  - random
  - validity >=0.5
  - validity-text >=0.3

tests:
  genvalidity-text-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - hspec
    - genvalidity
    - genvalidity-text
    - genvalidity-hspec

benchmarks:
  genvalidity-text-bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options:
    - -Wall
    dependencies:
    - QuickCheck
    - criterion
    - genvalidity
    - genvalidity-criterion
    - genvalidity-text
