name: genvalidity-text
version: '0.7.0.1'
synopsis: GenValidity support for Text
description: Please see README.md
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016-2020 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
dependencies:
- base >=4.7 && <5
- text
- QuickCheck

library:
  source-dirs: src
  exposed-modules:
  - Data.GenValidity.Text
  dependencies:
  - array
  - genvalidity >=0.5
  - random
  - validity >=0.5
  - validity-text >=0.3

tests:
  genvalidity-text-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-name-shadowing
    dependencies:
    - hspec
    - genvalidity
    - genvalidity-text
    - genvalidity-hspec

benchmarks:
  genvalidity-text-bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options:
    - -Wall
    dependencies:
    - QuickCheck
    - criterion
    - genvalidity
    - genvalidity-criterion
    - genvalidity-text
