name: genvalidity-text
version: '0.7.0.0'
synopsis: GenValidity support for Text
description: Please see README.md
category: Testing
author: Tom Sydney Kerckhove
maintainer:
- syd.kerckhove@gmail.com
- nick.van.den.broeck666@gmail.com
copyright: ! 'Copyright: (c) 2016-2019 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
dependencies:
- text
- QuickCheck

library:
  source-dirs: src
  exposed-modules:
  - Data.GenValidity.Text
  dependencies:
  - base >=4.7 && <5
  - validity >=0.5
  - validity-text >=0.3
  - genvalidity >=0.5
  - array

tests:
  genvalidity-text-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-name-shadowing
    dependencies:
    - base
    - hspec
    - genvalidity
    - genvalidity-text
    - genvalidity-hspec
