name: genvalidity-time
version: '0.2.1.2'
synopsis: GenValidity support for time
description: Please see README.md
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2017-2020 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
dependencies:
- base >=4.7 && <5
- time

library:
  source-dirs: src
  dependencies:
  - validity-time >=0.2
  - genvalidity >=0.5
  - QuickCheck

tests:
  genvalidity-time-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - genvalidity-time
    - hspec
    - genvalidity-hspec
