name: genvalidity-time
version: '1.0.0.1'
synopsis: GenValidity support for time
description: Please see README.md
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2016-2022 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity

extra-source-files:
- LICENSE
- CHANGELOG.md

dependencies:
- base >=4.7 && <5
- time

library:
  source-dirs: src
  dependencies:
  - validity-time >=0.2
  - genvalidity >= 1.0
  - QuickCheck

tests:
  genvalidity-time-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - genvalidity-time
    - hspec
    - genvalidity-hspec

benchmarks:
  genvalidity-time-bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - criterion
    - genvalidity-time
    - genvalidity-criterion >=1.1.0.0
