name: validity-unordered-containers
version: '0.2.0.2'
synopsis: Validity instances for unordered-containers
description: Please see README.md
category: Validity
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017-2020 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
dependencies:
- base >=4.7 && <5
- validity >=0.5
- unordered-containers >=0.2.7
- hashable
library:
  source-dirs: src
  exposed-modules:
  - Data.Validity.UnorderedContainers
  - Data.Validity.HashMap
  - Data.Validity.HashSet
