name: genvalidity-unordered-containers
version: '0.3.0.0'
synopsis: GenValidity support for unordered-containers
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2017-2020 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
dependencies:
- base <5
- unordered-containers

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - genvalidity >=0.8
  - hashable
  - validity >=0.5
  - validity-unordered-containers >=0.1

tests:
  genvalidity-unordered-containers-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - validity >=0.9
    - genvalidity >=0.7
    - genvalidity-hspec
    - genvalidity-unordered-containers
    - hspec
