name: genvalidity-unordered-containers
version: '0.1.0.0'
synopsis: GenValidity support for unordered-containers
description: Please see README.md
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
dependencies:
- unordered-containers
library:
  source-dirs: src
  exposed-modules:
  - Data.GenValidity.UnorderedContainers
  - Data.GenValidity.HashMap
  - Data.GenValidity.HashSet
  dependencies:
  - base <5
  - QuickCheck
  - genvalidity >=0.4 && <0.5
  - hashable
  - validity >=0.4 && <0.5
  - validity-unordered-containers >=0.1 && <0.2
tests:
  genvalidity-unordered-containers-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base >=4.9 && <=5
    - genvalidity
    - genvalidity-hspec
    - genvalidity-unordered-containers
    - hspec >=2.2 && <2.5
