name: validity-scientific
version: '0.1.0.0'
synopsis: Validity instances for scientific
description: Please see README.md
category: Web
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
dependencies:
- base >=4.7 && <5
- validity >=0.4 && <0.5
- scientific
library:
  source-dirs: src
  exposed-modules:
  - Data.Validity.Scientific
