name: genvalidity-hspec-binary
version: '0.2.0.3'
synopsis: Standard spec's for binary-related Instances
description: Standard spec's for cereal-related Instances, see https://hackage.haskell.org/package/binary.
category: Testing
author: Nick Van den Broeck
maintainer:
- syd.kerckhove@gmail.com
- nick.van.den.broeck666@gmail.com
copyright: 2017-2018 Tom Sydney Kerckhove
license: MIT
github: NorfairKing/validity
extra-source-files:
- README.md
dependencies:
- hspec

library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Test.Validity.Binary
  dependencies:
  - base >=4.9 && <=5
  - QuickCheck
  - binary
  - deepseq
  - genvalidity >=0.5
  - genvalidity-hspec >=0.6

tests:
  genvalidity-hspec-binary-doctests:
    main: DocTest.hs
    source-dirs: doctest
    ghc-options: -threaded
    dependencies:
    - QuickCheck
    - base
    - doctest
    - validity >=0.9
    - genvalidity >=0.7
    - genvalidity-property >=0.3
    - genvalidity-hspec-binary

  genvalidity-hspec-binary-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base
    - validity >=0.9
    - genvalidity >=0.7
    - genvalidity-property >=0.3
    - genvalidity-hspec-binary
