name: genvalidity-hspec
version: '0.7.0.2'
synopsis: Standard spec's for GenValidity instances
description: ! 'Note: There are companion packages for this library:


  * <https://hackage.haskell.org/package/genvalidity-hspec-aeson genvalidity-hspec-aeson>


  * <https://hackage.haskell.org/package/genvalidity-hspec-binary genvalidity-hspec-binary>


  * <https://hackage.haskell.org/package/genvalidity-hspec-cereal genvalidity-hspec-cereal>


  * <https://hackage.haskell.org/package/genvalidity-hspec-hashable genvalidity-hspec-hashable>'
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016-2019 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
extra-source-files:
- CHANGELOG.md
dependencies:
- QuickCheck
- hspec-core

library:
  source-dirs: src
  dependencies:
  - base >=4.9 && <5
  - genvalidity >=0.8
  - genvalidity-property >=0.5
  - hspec
  - transformers
  - validity >=0.5

tests:
  genvalidity-hspec-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base
    - genvalidity
    - genvalidity-hspec
    - hspec
