name: validity-aeson
version: '0.1.0.0'
synopsis: Validity instances for aeson
description: Please see README.md
category: Validity
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
dependencies:
- base >=4.7 && <5
- aeson
- validity >=0.4 && <0.5
- validity-text >=0.2 && <0.3
- validity-unordered-containers >=0.1 && <0.2
- validity-vector >=0.1 && <0.2
- validity-scientific >=0.1 && <0.2
library:
  source-dirs: src
  exposed-modules:
  - Data.Validity.Aeson
