name: genvalidity-hspec-aeson
version: '0.3.1.0'
synopsis: Standard spec's for aeson-related instances
description: Standard spec's for aeson-related Instances
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016-2020 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
homepage: http://cs-syd.eu
dependencies:
- hspec

library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Test.Validity.Aeson
  dependencies:
  - base >=4.9 && <=5
  - genvalidity-hspec >=0.6
  - genvalidity >=0.5
  - aeson
  - QuickCheck
  - deepseq
  - bytestring

tests:
  genvalidity-hspec-aeson-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - aeson
    - base
    - genvalidity >=0.7
    - genvalidity-aeson
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-property >=0.3
    - genvalidity-text
    - text
    - validity >=0.9
