name: genvalidity-hspec-hashable
version: '0.2.0.4'
synopsis: Standard spec's for Hashable instances
description: Standard spec's for Hashable instances
category: Testing
author: Nick Van den Broeck
maintainer: syd@cs-syd.eu
copyright: 2017-2020 Tom Sydney Kerckhove
license: MIT
github: NorfairKing/validity
extra-source-files:
- README.md
dependencies:
- base >=4.9 && <5
- hashable >=1.2
- QuickCheck

library:
  source-dirs: src
  dependencies:
  - validity >=0.5
  - genvalidity-hspec >=0.6
  - genvalidity >=0.5
  - genvalidity-property >=0.2
  - hspec

tests:
  genvalidity-hspec-hashable-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - validity >=0.9
    - genvalidity >=0.7
    - genvalidity-property >=0.3
    - genvalidity-hspec
    - genvalidity-hspec-hashable
    - hashable
    - hspec
    - hspec-core
