name: genvalidity-aeson
version: '0.1.0.0'
synopsis: GenValidity support for aeson
description: Please see README.md
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
dependencies:
- aeson
library:
  source-dirs: src
  exposed-modules:
  - Data.GenValidity.Aeson
  dependencies:
  - base <5
  - QuickCheck
  - genvalidity >=0.4 && <0.5
  - validity >=0.4 && <0.5
  - validity-aeson >=0.1 && <0.2
  - genvalidity-text >=0.4 && <0.5
  - genvalidity-vector >=0.1 && <0.2
  - genvalidity-unordered-containers >=0.1 && <0.2
  - genvalidity-scientific >=0.1 && <0.2
tests:
  genvalidity-aeson-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base >=4.9 && <=5
    - genvalidity
    - genvalidity-hspec
    - genvalidity-aeson
    - hspec >=2.2 && <2.5
