name: genvalidity-persistent
version: '1.0.0.0'
synopsis: GenValidity support for Persistent
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2016-2021 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity

extra-source-files:
- LICENSE
- CHANGELOG.md

dependencies:
- base >=4.7 && <5
- persistent >=0.5

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - containers
  - genvalidity >=1.0
  - genvalidity-containers
  - validity-containers
  - validity-persistent

tests:
  genvalidity-persistent-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - genvalidity
    - genvalidity-hspec
    - genvalidity-persistent
    - hspec
    - persistent-template
    - validity-containers

benchmarks:
  genvalidity-persistent-bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - criterion
    - deepseq
    - genvalidity
    - genvalidity-criterion
    - genvalidity-persistent
    - persistent-template
