name: genvalidity-sydtest-aeson
version: '0.0.0.0'
synopsis: Standard spec's for aeson-related instances in sydtest
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2020 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
homepage: http://cs-syd.eu
dependencies:
- base >=4.9 && <=5
- sydtest

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - genvalidity-sydtest
  - genvalidity >=0.5
  - aeson
  - QuickCheck
  - deepseq
  - bytestring

tests:
  genvalidity-sydtest-aeson-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - aeson
    - genvalidity >=0.7
    - genvalidity-aeson
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text
    - text
    - validity >=0.9
