name: validity-primitive
version: '0.0.0.0'
synopsis: Validity instances for primitive
category: Validity
author: Nick Van den Broeck
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2017-2020 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity

dependencies:
- base >=4.7 && <5
- validity >=0.5
- primitive

library:
  source-dirs: src
