name: genvalidity-bytestring
version: '1.0.0.1'
synopsis: GenValidity support for ByteString
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2016-2022 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity

extra-source-files:
- LICENSE
- CHANGELOG.md

dependencies:
- base >=4.7 && <5
- bytestring
- QuickCheck

library:
  source-dirs: src
  dependencies:
  - validity >=0.5
  - validity-bytestring >=0.4
  - genvalidity >=1.0
  - random

tests:
  genvalidity-bytestring-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - deepseq
    - validity >=0.9
    - genvalidity
    - genvalidity-bytestring
    - genvalidity-hspec
    - hspec

benchmarks:
  genvalidity-bytestring-bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options:
    - -Wall
    dependencies:
    - QuickCheck
    - criterion
    - genvalidity
    - genvalidity-criterion >=1.1.0.0
    - genvalidity-bytestring
