name: genvalidity-bytestring
version: '0.5.0.1'
synopsis: GenValidity support for ByteString
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2016-2020 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
dependencies:
- base >=4.7 && <5
- bytestring
- QuickCheck

library:
  source-dirs: src
  dependencies:
  - validity >=0.5
  - validity-bytestring >=0.4
  - genvalidity >=0.8

tests:
  genvalidity-bytestring-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - deepseq
    - validity >= 0.9
    - genvalidity >= 0.7
    - genvalidity-bytestring
    - genvalidity-hspec
    - hspec
