name: genvalidity-uuid
version: '1.0.0.1'
synopsis: GenValidity support for UUID
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2016-2022 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity

extra-source-files:
- LICENSE
- CHANGELOG.md

dependencies:
- base >=4.7 && <5
- QuickCheck
- uuid

library:
  source-dirs: src
  dependencies:
  - genvalidity >= 1.0
  - validity >=0.5
  - validity-uuid >=0.0

tests:
  genvalidity-uuid-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-name-shadowing
    dependencies:
    - base
    - genvalidity
    - genvalidity-hspec
    - genvalidity-uuid
    - hspec

benchmarks:
  genvalidity-uuid-bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options:
    - -Wall
    dependencies:
    - QuickCheck
    - criterion
    - genvalidity
    - genvalidity-criterion >= 1.0.0.1
    - genvalidity-uuid

