name: genvalidity-containers
version: '0.8.0.1'
synopsis: GenValidity support for containers
description: Please see README.md
category: Testing
author: Tom Sydney Kerckhove
maintainer:
- syd.kerckhove@gmail.com
- nick.van.den.broeck666@gmail.com
copyright: ! 'Copyright: (c) 2016-2019 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
extra-source-files:
- CHANGELOG.md
dependencies:
- base >=4.9 && <=5
- containers

library:
  source-dirs: src
  exposed-modules:
  - Data.GenValidity.Containers
  - Data.GenValidity.Map
  - Data.GenValidity.Sequence
  - Data.GenValidity.Set
  - Data.GenValidity.Tree
  dependencies:
  - QuickCheck
  - genvalidity >=0.8
  - validity >=0.5
  - validity-containers >=0.3

tests:
  genvalidity-containers-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - validity >=0.9
    - genvalidity >=0.7
    - genvalidity-containers >=0.5
    - genvalidity-property >=0.5
    - genvalidity-hspec
    - hspec

benchmarks:
  genvalidity-containers-bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options:
    - -Wall
    dependencies:
    - QuickCheck
    - criterion
    - genvalidity-containers
    - genvalidity-criterion
